#
# Goal:
# * Test currently supported and recently sunsetted versions of both
#   Symfony and PHP.
# * Test future releases of both.
#

language: php
jobs:
  include:
    # test Symfony 3.4 on PHP 7.1
    - php: 7.1
      env: SYMFONY=~3.4.0 SKIP_SYNTAX=1
    # test Symfony 4.0-4.3 on PHP 7.2
    - php: 7.2
      env: SYMFONY=~4.0.0
    - php: 7.2
      env: SYMFONY=~4.1.0
    - php: 7.2
      env: SYMFONY=~4.2.0
    - php: 7.2
      env: SYMFONY=~4.3.0
    # test Symfony 4.4 on PHP 7.3
    - php: 7.3
      env: SYMFONY=~4.4.0
    # test Symfony 5.0 on PHP 7.4
    - php: 7.4
      env: SYMFONY=~5.0.0
    # test Symfony dev-master on PHP nightly
    - php: nightly
      env: SYMFONY=dev-master COMPOSER_ARGS=--ignore-platform-reqs
  # allow php-nightly to fail
  allow_failures:
    php: nightly

before_script:
  - jq 'del(."require-dev")' composer.json > composer-ci.json
  - [ "$SYMFONY" = "dev-master" ] && composer config minimum-stability dev
  - COMPOSER=composer-ci.json composer require $COMPOSER_ARGS symfony/http-foundation:$SYMFONY
  - COMPOSER=composer-ci.json composer require $COMPOSER_ARGS --dev phpunit/phpunit
  - [ -z "$SKIP_SYNTAX" ] && composer install && composer phpcs && composer phpstan

script: vendor/bin/phpunit

