language: php
php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
env:
  - SYMFONY=^3.4
  - SYMFONY=^4.4
  - SYMFONY=^5.0
  - SYMFONY=dev-master
jobs:
  exclude:
    - php: 7.1
      env: SYMFONY=^5.0
    - php: 7.1
      env: SYMFONY=dev-master

before_script:
  - jq 'del(."require-dev")' composer.json > composer-ci.json
  - COMPOSER=composer-ci.json composer require symfony/http-foundation:$SYMFONY
  - COMPOSER=composer-ci.json composer require --dev phpunit/phpunit

script: vendor/bin/phpunit

